import type { Metadata, Viewport } from "next";
import "./globals.css";

import ClientLayout from "@/components/navigation/ClientLayout";
import { ToastContainer } from "react-toastify";
import ClerkAndConvexProvider from "@/providers/ClerkAndConvexProvider";
import PublicNavBar from "@/components/navigation/PublicNavBar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export const viewport: Viewport = {
    width: "device-width",
    initialScale: 1,
    viewportFit: "cover",
    userScalable: false,
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            {/* ✅ Step 1b: Wrap app in ClerkProvider */}
            <ClerkAndConvexProvider>
                <body>
                    <div className="app-wrapper">
                        <PublicNavBar />
                        <ClientLayout>{children}</ClientLayout>
                        <ToastContainer position="top-center" />
                    </div>
                </body>
            </ClerkAndConvexProvider>
        </html>
    );
}
