import type { Metadata } from "next";
import "./globals.css";

import ClientLayout from "@/components/navigation/ClientLayout";
import { ToastContainer } from "react-toastify";
import ClerkAndConvexProvider from "@/providers/ClerkAndConvexProvider";
import PublicNavBar from "@/components/navigation/PublicNavBar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    viewport: "width=device-width, initial-scale=1, viewport-fit=cover",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            {/* ✅ Step 1b: Wrap app in ClerkProvider */}
            <ClerkAndConvexProvider>
                <body>
                    <div className="app-wrapper">
                        <PublicNavBar />
                        <ClientLayout>{children}</ClientLayout>
                        <ToastContainer position="top-center" />
                    </div>
                </body>
            </ClerkAndConvexProvider>
        </html>
    );
}
